version: '3'
services:
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./web:/var/www/html
        expose:
            - "80"
        ports:
            - 8080:80
        restart: always
        depends_on:
            - php

    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        restart: always
        expose:
            - "9000"
        volumes:
            - ./web:/var/www/html

        ## --------------------------------------------
        ## | 4 : database server
        ## --------------------------------------------
    mysqldb:

        image: mysql:8.0.21
        container_name: mysqldb
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        ports:
            - "3306:3306"
        volumes:
            - "./data/Database/mysql:/var/lib/mysql"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysqldb
        expose:
            - '80'
            - '443'
        environment:
            - PMA_HOST=mysqldb
        volumes:
            - /sessions
        ports:
            - 8010:80
